import { useMemo, useState } from "react";
import { Download, Fingerprint, FileCheck2, FolderOpen, Hash, MapPin, Pencil, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { useAuth } from "@/contexts/AuthContext";
import { attachments } from "@/lib/attachments";
import { audit, custody, documents, evidence as evidenceStore, fingerprints, locations } from "@/lib/storage";
import { CONFIDENCE_LEVELS, CUSTODY_ACTIONS, type CustodyAction, type ConfidenceLevel, type Investigation, type CustodyEvent, type FingerprintRecord, type DocumentRecord, type Location } from "@/lib/types";

const dateNow = () => new Date().toISOString().slice(0, 10);
const fmt = (d: string) => d ? new Date(d).toLocaleDateString("pt-BR") : "—";

export function ForensicsTab({ inv, onRefresh }: { inv: Investigation; onRefresh: () => void }) {
  const { user } = useAuth();
  const [custodyOpen, setCustodyOpen] = useState(false);
  const [fingerOpen, setFingerOpen] = useState(false);
  const [docOpen, setDocOpen] = useState(false);
  const [locationOpen, setLocationOpen] = useState(false);
  const [editingCustody, setEditingCustody] = useState<CustodyEvent | null>(null);
  const [editingFinger, setEditingFinger] = useState<FingerprintRecord | null>(null);
  const [editingDoc, setEditingDoc] = useState<DocumentRecord | null>(null);
  const [editingLocation, setEditingLocation] = useState<Location | null>(null);
  const [custodyForm, setCustodyForm] = useState({ evidenceId: "", date: dateNow(), time: "", responsible: "", origin: "", destination: "", action: "Coleta" as CustodyAction, description: "", condition: "", notes: "" });
  const [fingerForm, setFingerForm] = useState({ finger: "Indicador", hand: "Direita" as "Direita" | "Esquerda", classification: "", quality: "Média" as ConfidenceLevel, location: "", date: dateNow(), responsible: "", method: "Fotografia", notes: "" });
  const [docForm, setDocForm] = useState({ name: "", type: "Laudo", description: "", origin: "", date: dateNow(), number: "", responsible: "", notes: "" });
  const [locationForm, setLocationForm] = useState({ name: "", address: "", reference: "", latitude: "", longitude: "", description: "", notes: "" });
  const evidence = useMemo(() => user ? evidenceStore.listByInvestigation(user.id, inv.id) : [], [user, inv.id]);
  const custodyItems = user ? custody.listByInvestigation(user.id, inv.id) : [];
  const fingerItems = user ? fingerprints.listByInvestigation(user.id, inv.id) : [];
  const docItems = user ? documents.listByInvestigation(user.id, inv.id) : [];
  const locationItems = user ? locations.listByInvestigation(user.id, inv.id) : [];
  const files = user ? attachments.list(user.id, inv.id) : [];

  const saveCustody = (e: React.FormEvent) => { e.preventDefault(); if (!user || !custodyForm.evidenceId || !custodyForm.responsible) { toast.error("Selecione uma evidência e informe o responsável."); return; } if (editingCustody) { custody.update(user.id, editingCustody.id, custodyForm); toast.success("Movimentação atualizada."); } else { custody.create(user.id, { investigationId: inv.id, ...custodyForm }); toast.success("Movimentação registrada."); } audit.create(user.id, { investigationId: inv.id, action: "Cadeia de custódia atualizada", entity: "custody", description: `${custodyForm.action} registrada` }); setEditingCustody(null); setCustodyOpen(false); onRefresh(); };
  const saveFinger = (e: React.FormEvent) => { e.preventDefault(); if (!user || !fingerForm.responsible) { toast.error("Informe o responsável."); return; } if (editingFinger) { fingerprints.update(user.id, editingFinger.id, fingerForm); toast.success("Impressão digital atualizada."); } else { fingerprints.create(user.id, { investigationId: inv.id, ...fingerForm }); toast.success("Impressão digital cadastrada."); } setEditingFinger(null); onRefresh(); setFingerOpen(false); };
  const saveDoc = (e: React.FormEvent) => { e.preventDefault(); if (!user || !docForm.name.trim()) return; if (editingDoc) { documents.update(user.id, editingDoc.id, docForm); toast.success("Documento atualizado."); } else { documents.create(user.id, { investigationId: inv.id, ...docForm }); toast.success("Documento registrado."); } setEditingDoc(null); onRefresh(); setDocOpen(false); };
  const saveLocation = (e: React.FormEvent) => { e.preventDefault(); if (!user || !locationForm.name.trim()) return; if (editingLocation) { locations.update(user.id, editingLocation.id, locationForm); toast.success("Local atualizado."); } else { locations.create(user.id, { investigationId: inv.id, ...locationForm }); toast.success("Local cadastrado."); } setEditingLocation(null); onRefresh(); setLocationOpen(false); };
  const startEditCustody = (item: CustodyEvent) => { setEditingCustody(item); setCustodyForm({ evidenceId: item.evidenceId, date: item.date, time: item.time, responsible: item.responsible, origin: item.origin, destination: item.destination, action: item.action, description: item.description, condition: item.condition, notes: item.notes }); setCustodyOpen(true); };
  const startEditFinger = (item: FingerprintRecord) => { setEditingFinger(item); setFingerForm({ finger: item.finger, hand: item.hand, classification: item.classification, quality: item.quality, location: item.location, date: item.date, responsible: item.responsible, method: item.method, notes: item.notes }); setFingerOpen(true); };
  const startEditDoc = (item: DocumentRecord) => { setEditingDoc(item); setDocForm({ name: item.name, type: item.type, description: item.description, origin: item.origin, date: item.date, number: item.number, responsible: item.responsible, notes: item.notes }); setDocOpen(true); };
  const startEditLocation = (item: Location) => { setEditingLocation(item); setLocationForm({ name: item.name, address: item.address, reference: item.reference, latitude: item.latitude, longitude: item.longitude, description: item.description, notes: item.notes }); setLocationOpen(true); };

  const remove = (store: { remove: (owner: string, id: string) => void }, id: string) => { if (!user) return; store.remove(user.id, id); onRefresh(); };
  const exportCase = () => { if (!user) return; const payload = { format: "nexus", version: 4, exportedAt: new Date().toISOString(), investigation: inv, evidence, custody: custodyItems, fingerprints: fingerItems, documents: docItems, locations: locationItems, attachments: files }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `NEXUS-${inv.title.replace(/[^a-z0-9]+/gi, "-")}.nexus.json`; a.click(); URL.revokeObjectURL(url); toast.success("Pacote JSON exportado."); };
  const integrity = () => { const lines = [`RELATÓRIO DE INTEGRIDADE — ${inv.title}`, `Gerado em: ${new Date().toLocaleString("pt-BR")}`, "", ...files.map((f) => `${f.name}\nTamanho: ${f.size}\nSHA-256: ${f.sha256 || "Não calculado"}\nData: ${f.hashCalculatedAt || "—"}\nStatus: ${f.sha256 ? "Hash registrado para verificação de integridade" : "Não verificado"}\n`)]; const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "relatorio-integridade.txt"; a.click(); URL.revokeObjectURL(url); };

  return <div className="space-y-4"><div className="rounded-md border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-amber-100"><strong>Registro auxiliar:</strong> cadeia de custódia, hashes e comparações deste módulo são controles digitais locais. Não constituem, por si só, cadeia de custódia jurídica oficial nem declaração automática de autenticidade.</div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card><CardContent className="pt-5"><p className="text-2xl font-semibold">{evidence.length}</p><p className="text-xs text-muted-foreground">Evidências</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-2xl font-semibold">{files.length}</p><p className="text-xs text-muted-foreground">Arquivos originais</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-2xl font-semibold">{custodyItems.length}</p><p className="text-xs text-muted-foreground">Registros de custódia</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-2xl font-semibold">{fingerItems.length}</p><p className="text-xs text-muted-foreground">Impressões digitais</p></CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><div className="flex justify-between gap-2"><div><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4 text-primary" /> Cadeia de custódia</CardTitle><CardDescription>Histórico cronológico por evidência.</CardDescription></div><Button size="sm" onClick={() => setCustodyOpen(true)}><Plus className="h-4 w-4" /> Registrar</Button></div></CardHeader><CardContent>{custodyItems.length ? <div className="space-y-2">{custodyItems.map((c) => <div key={c.id} className="rounded border p-3"><div className="flex justify-between"><strong>{c.action}</strong><div className="flex gap-1"><Button variant="ghost" size="icon" title="Editar" onClick={() => startEditCustody(c)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => remove(custody, c.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div><p className="text-xs text-muted-foreground">{fmt(c.date)} {c.time} • {c.responsible}</p><p className="text-sm">{c.description}</p><p className="text-xs text-muted-foreground">{c.origin} → {c.destination}</p></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">Nenhuma movimentação registrada.</p>}</CardContent></Card>
    <Card><CardHeader><div className="flex justify-between gap-2"><div><CardTitle className="flex items-center gap-2 text-base"><Fingerprint className="h-4 w-4 text-primary" /> Impressões digitais</CardTitle><CardDescription>Cadastro pericial sem reconhecimento automático.</CardDescription></div><Button size="sm" onClick={() => setFingerOpen(true)}><Plus className="h-4 w-4" /> Cadastrar</Button></div></CardHeader><CardContent>{fingerItems.length ? <div className="space-y-2">{fingerItems.map((f) => <div key={f.id} className="rounded border p-3"><div className="flex justify-between"><strong>{f.finger} {f.hand}</strong><div className="flex gap-1"><Button variant="ghost" size="icon" title="Editar" onClick={() => startEditFinger(f)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => remove(fingerprints, f.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div><p className="text-xs text-muted-foreground">{f.method} • Qualidade {f.quality} • {f.responsible}</p><p className="text-sm">{f.classification || "Classificação não informada"}</p></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">Nenhuma impressão cadastrada.</p>}</CardContent></Card>
    <Card><CardHeader><div className="flex justify-between gap-2"><div><CardTitle className="flex items-center gap-2 text-base"><FolderOpen className="h-4 w-4 text-primary" /> Documentos relacionados</CardTitle><CardDescription>BOs, processos, ofícios e laudos.</CardDescription></div><Button size="sm" onClick={() => setDocOpen(true)}><Plus className="h-4 w-4" /> Registrar</Button></div></CardHeader><CardContent>{docItems.length ? <div className="space-y-2">{docItems.map((d) => <div key={d.id} className="rounded border p-3"><div className="flex justify-between"><strong>{d.name}</strong><div className="flex gap-1"><Button variant="ghost" size="icon" title="Editar" onClick={() => startEditDoc(d)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => remove(documents, d.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div><p className="text-xs text-muted-foreground">{d.type} • {d.number || "Sem número"} • {fmt(d.date)}</p><p className="text-sm">{d.description}</p></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">Nenhum documento registrado.</p>}</CardContent></Card>
    <Card><CardHeader><div className="flex justify-between gap-2"><div><CardTitle className="flex items-center gap-2 text-base"><MapPin className="h-4 w-4 text-primary" /> Locais</CardTitle><CardDescription>Cenas, endereços e pontos relacionados.</CardDescription></div><Button size="sm" onClick={() => setLocationOpen(true)}><Plus className="h-4 w-4" /> Cadastrar</Button></div></CardHeader><CardContent>{locationItems.length ? <div className="space-y-2">{locationItems.map((l) => <div key={l.id} className="rounded border p-3"><div className="flex justify-between"><strong>{l.name}</strong><div className="flex gap-1"><Button variant="ghost" size="icon" title="Editar" onClick={() => startEditLocation(l)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => remove(locations, l.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div><p className="text-xs text-muted-foreground">{l.address} {l.latitude && `• ${l.latitude}, ${l.longitude}`}</p><p className="text-sm">{l.description}</p></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">Nenhum local cadastrado.</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Hash className="h-4 w-4 text-primary" /> Integridade e backup</CardTitle><CardDescription>Os hashes SHA-256 são calculados no dispositivo e indicam correspondência de bytes, não autenticidade jurídica.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><Button variant="outline" onClick={exportCase}><Download className="h-4 w-4" /> Exportar investigação</Button><Button variant="outline" onClick={integrity}><FileCheck2 className="h-4 w-4" /> Relatório de integridade</Button><Badge variant="secondary">Use a aba Anexos para consultar hashes e arquivos</Badge></CardContent></Card>
    <Dialog open={custodyOpen} onOpenChange={setCustodyOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{editingCustody ? "Editar movimentação" : "Registrar cadeia de custódia"}</DialogTitle><DialogDescription>Registro auxiliar local, sem pretensão de validade oficial.</DialogDescription></DialogHeader><form onSubmit={saveCustody} className="grid gap-3 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label>Evidência</Label><Select value={custodyForm.evidenceId} onValueChange={(v) => setCustodyForm({ ...custodyForm, evidenceId: v })}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{evidence.map((e) => <SelectItem key={e.id} value={e.id}>{e.code || e.name} — {e.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Data</Label><Input type="date" value={custodyForm.date} onChange={(e) => setCustodyForm({ ...custodyForm, date: e.target.value })} /></div><div className="space-y-2"><Label>Hora</Label><Input type="time" value={custodyForm.time} onChange={(e) => setCustodyForm({ ...custodyForm, time: e.target.value })} /></div><div className="space-y-2"><Label>Ação</Label><Select value={custodyForm.action} onValueChange={(v) => setCustodyForm({ ...custodyForm, action: v as CustodyAction })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{CUSTODY_ACTIONS.map((a) => <SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Responsável</Label><Input value={custodyForm.responsible} onChange={(e) => setCustodyForm({ ...custodyForm, responsible: e.target.value })} /></div><div className="space-y-2"><Label>Origem</Label><Input value={custodyForm.origin} onChange={(e) => setCustodyForm({ ...custodyForm, origin: e.target.value })} /></div><div className="space-y-2"><Label>Destino</Label><Input value={custodyForm.destination} onChange={(e) => setCustodyForm({ ...custodyForm, destination: e.target.value })} /></div><div className="space-y-2 sm:col-span-2"><Label>Descrição</Label><Textarea value={custodyForm.description} onChange={(e) => setCustodyForm({ ...custodyForm, description: e.target.value })} /></div><DialogFooter className="sm:col-span-2"><Button type="submit">{editingCustody ? "Salvar alterações" : "Registrar movimentação"}</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={fingerOpen} onOpenChange={setFingerOpen}><DialogContent><DialogHeader><DialogTitle>{editingFinger ? "Editar impressão digital" : "Nova impressão digital"}</DialogTitle></DialogHeader><form onSubmit={saveFinger} className="space-y-3"><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Dedo</Label><Input value={fingerForm.finger} onChange={(e) => setFingerForm({ ...fingerForm, finger: e.target.value })} /></div><div className="space-y-2"><Label>Mão</Label><Select value={fingerForm.hand} onValueChange={(v) => setFingerForm({ ...fingerForm, hand: v as "Direita" | "Esquerda" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Direita">Direita</SelectItem><SelectItem value="Esquerda">Esquerda</SelectItem></SelectContent></Select></div></div><Input placeholder="Classificação" value={fingerForm.classification} onChange={(e) => setFingerForm({ ...fingerForm, classification: e.target.value })} /><Input placeholder="Local de coleta" value={fingerForm.location} onChange={(e) => setFingerForm({ ...fingerForm, location: e.target.value })} /><Input placeholder="Responsável" value={fingerForm.responsible} onChange={(e) => setFingerForm({ ...fingerForm, responsible: e.target.value })} /><Input placeholder="Método: tinta, pó, fotografia, scanner..." value={fingerForm.method} onChange={(e) => setFingerForm({ ...fingerForm, method: e.target.value })} /><DialogFooter><Button type="submit">{editingFinger ? "Salvar alterações" : "Cadastrar"}</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={docOpen} onOpenChange={setDocOpen}><DialogContent><DialogHeader><DialogTitle>{editingDoc ? "Editar documento" : "Novo documento"}</DialogTitle></DialogHeader><form onSubmit={saveDoc} className="space-y-3"><Input placeholder="Nome *" value={docForm.name} onChange={(e) => setDocForm({ ...docForm, name: e.target.value })} autoFocus /><Input placeholder="Tipo: BO, processo, ofício, laudo..." value={docForm.type} onChange={(e) => setDocForm({ ...docForm, type: e.target.value })} /><Input placeholder="Número" value={docForm.number} onChange={(e) => setDocForm({ ...docForm, number: e.target.value })} /><Input placeholder="Origem" value={docForm.origin} onChange={(e) => setDocForm({ ...docForm, origin: e.target.value })} /><Textarea placeholder="Descrição" value={docForm.description} onChange={(e) => setDocForm({ ...docForm, description: e.target.value })} /><DialogFooter><Button type="submit">{editingDoc ? "Salvar alterações" : "Registrar"}</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={locationOpen} onOpenChange={setLocationOpen}><DialogContent><DialogHeader><DialogTitle>{editingLocation ? "Editar local" : "Novo local"}</DialogTitle></DialogHeader><form onSubmit={saveLocation} className="space-y-3"><Input placeholder="Nome *" value={locationForm.name} onChange={(e) => setLocationForm({ ...locationForm, name: e.target.value })} autoFocus /><Input placeholder="Endereço" value={locationForm.address} onChange={(e) => setLocationForm({ ...locationForm, address: e.target.value })} /><div className="grid grid-cols-2 gap-3"><Input placeholder="Latitude" value={locationForm.latitude} onChange={(e) => setLocationForm({ ...locationForm, latitude: e.target.value })} /><Input placeholder="Longitude" value={locationForm.longitude} onChange={(e) => setLocationForm({ ...locationForm, longitude: e.target.value })} /></div><Input placeholder="Referência" value={locationForm.reference} onChange={(e) => setLocationForm({ ...locationForm, reference: e.target.value })} /><Textarea placeholder="Descrição" value={locationForm.description} onChange={(e) => setLocationForm({ ...locationForm, description: e.target.value })} /><DialogFooter><Button type="submit">{editingLocation ? "Salvar alterações" : "Cadastrar"}</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}
